name: Test Go

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'
    paths:
      - '**.go'
      - .github/workflows/go.yml
      - "go.mod"
      - "go.sum"


jobs:
  test:
    permissions:
        security-events: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [ '1.18', '1.19', '1.20', '1.21', '1.22', '1.23', '1.24', ]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on

    steps:
    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ matrix.go }}
        cache: false

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Test
      run: make test

    - name: Benchmark
      run: make bench

    - uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
      with:
        files: c.out
        fail_ci_if_error: true
        env_vars: GO,OS
      env:
        GO: ${ { matrix.go }}
        OS: ${{ runner.os }}
