name: Golanglint CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'go.sum'
      - 'go.mod'
      - '**.go'
      - .github/workflows/golangci-lint.yml
      - '.golangci-lint.yml'
  pull_request:
    branches:
      - main

jobs:
  Go:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: latest
          args: "--config .golangci-lint.yml"
