name: Golanglint CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'go.sum'
      - 'go.mod'
      - '**.go'
      - .github/workflows/golangci-lint.yml
  pull_request:
    branches:
      - main

jobs:
  Go:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: "--config .golangci-lint.yml"
